# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies, ignore prepare scripts to avoid build issues on install
RUN npm install --ignore-scripts

# Copy rest of the source code
COPY . .

# Build the project
RUN npm run build

# Expose port if needed (usually MCP servers listen on stdio, but if using API, consider exposing)

# Use the node command to run the built server
CMD ["node", "./build/index.js"]
